name: Deploy Next.js to cPanel via SSH

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js for build
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # You can specify the Node.js version you need

      # Step 3: Install dependencies and build the Next.js project
      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      # Step 4: Deploy files via FTP (Optional, if you're uploading files directly via FTP)
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .next/  # Upload only the .next folder (built files)
          server-dir: /public_html/  # Target directory on your cPanel server
          exclude: |
            .git*
            *.md
            README.md
            .github/
            node_modules/  # Exclude node_modules
            .next/cache/

      # Step 5: SSH into cPanel server and deploy Next.js app
      # - name: SSH into cPanel server and deploy
      #   uses: appleboy/ssh-action@v0.1.3
      #   with:
      #     host: ${{ secrets.CPANEL_SERVER_IP }}  # cPanel server IP address
      #     username: ${{ secrets.CPANEL_USERNAME }}  # SSH username
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key stored in GitHub Secrets
      #     port: 22  # Default SSH port
      #     script: |
      #       cd /home/${{ secrets.CPANEL_USERNAME }}/public_html/  # Path to your Next.js app
      #       npm install  # Run npm install if dependencies aren't installed yet
      #       npm run build  # Ensure the app is built correctly
      #       pm2 start npm --name "next-app" -- start  # Run the Next.js app with PM2
      #       pm2 save  # Save the PM2 process for automatic restart

      # # Step 6: (Optional) Clean up old files or restart services if needed
      # - name: Cleanup and restart services
      #   run: |
      #     # Example cleanup command or additional commands to restart services
      #     echo "Cleaning up and restarting services"
