name: Deploy Next.js to cPanel via FTP and SSH

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js for build
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  # Use the appropriate Node version for your project

      # Step 3: Install dependencies and build Next.js project
      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      # Step 4: Deploy files via FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Upload all files (including package.json, .next/, etc.)
          server-dir: /public_html/  # Target directory on your cPanel server
          exclude: |
            .git*
            *.md
            README.md
            .github/
            node_modules/
            .next/cache/

      # Step 5: SSH into the cPanel server and run npm install and npm run build
      - name: SSH into cPanel server and install dependencies
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.CPANEL_SERVER_IP }}  # cPanel server IP
          username: ${{ secrets.CPANEL_USERNAME }}  # SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Your private SSH key
          port: 22
          script: |
            cd /home/refsuz/refs.uz/ftp_refsuz/public_html/  # Path to your app
            npm install
            npm run build
            pm2 start npm --name "next-app" -- start  # Run the Next.js app with PM2
            pm2 save  # Make sure PM2 remembers the process
